### ISSUE TITLE
missing keys

### ISSUE THREAD

**Issue by cgreaney** [danrspencer/concourse-ssh-scp-resource#1]
I'm getting the following error.  I'm using user name/password parameters - not using a key 

Traceback (most recent call last):
  File "/opt/resource/out", line 39, in <module>
    main(path, config)
  File "/opt/resource/out", line 22, in main
    validate_schema(config, config_schema)
  File "/opt/resource/shared.py", line 19, in validate_schema
    validate_schema(target[key], schema[key], "%s." % key)
  File "/opt/resource/shared.py", line 13, in validate_schema
    raise ValueError("Expected to find '%s%s' value in config" % (prefix, key))
ValueError: Expected to find 'source.private_key' value in config

**Comment by danrspencer** [comment]
I don't think I ever finished work on this resource, sorry. Feel free to fork it and carry on where I left off though.
